import { sitePath } from "@/lib/site-path";
import { CultivationStory, CompanyFAQ } from "@/components/company-depth";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Droplets, Eye, Leaf, Microscope, Sun, Waves } from "lucide-react";

export const metadata = { title:"About Sea Pearl Biotech | Cultivation and Ingredient Manufacturing" };
export default function AboutPage(){return <main><div className="page-top"><SiteHeader dark={false}/><div className="page-hero"><p className="section-label">About Sea Pearl Biotech</p><h1>Biotechnology rooted<br/>in living systems.</h1><p>Founded in March 2016 in Ahmedabad, Gujarat, Sea Pearl Biotech focuses on the cultivation, manufacturing and marketing of spirulina and algae-based ingredients.</p></div></div>
<figure className="section about-photo"><img src={sitePath("/original/PHOTO-2024-07-12-12-50-31-2.jpg")} alt="Sea Pearl spirulina cultivation ponds"/><figcaption>Our cultivation environment in Gujarat.</figcaption></figure><section className="section editorial-grid"><div><p className="section-label">Our perspective</p><h2>Natural inputs.<br/>Precise thinking.</h2></div><div className="long-copy"><p>We work at the meeting point of cultivation and product development. Our role extends from growing spirulina to helping B2B teams consider ingredient formats for food, supplement, cosmetic, agriculture and animal-nutrition applications.</p><p>Our work also includes product formulation, packaging and labelling support for businesses developing their own spirulina range. We collaborate with brands to understand their product vision and the requirements of their market.</p></div></section>
<section className="section value-grid">{[{i:Eye,t:"Mission",p:"Connect human wellbeing and environmental responsibility through spirulina, education and sustainable innovation."},{i:Sun,t:"Vision",p:"Develop natural functional foods and health supplements for local and global markets."},{i:Leaf,t:"Approach",p:"Cultivate responsibly, support product development and build long-term relationships with brands and ingredient buyers."}].map(({i:I,t,p})=><div className="value-card" key={t}><I/><h3>{t}</h3><p>{p}</p></div>)}</section>
<section className="dark-story"><div className="section"><div className="section-heading split-heading"><div><p className="section-label light">Cultivation environment</p><h2>Where biology meets process control.</h2></div><p>Our cultivation approach brings water management, nutrient supply, harvesting and quality-control checkpoints together. The growing environment is the starting point for the ingredients we supply.</p></div><div className="story-flow">{[{i:Waves,t:"Cultivate",p:"Managed growing environments"},{i:Droplets,t:"Monitor",p:"Water and nutrient conditions"},{i:Microscope,t:"Review",p:"Testing and quality checkpoints"},{i:Leaf,t:"Develop",p:"Ingredient and format support"}].map(({i:I,t,p},n)=><div key={t}><span>0{n+1}</span><I/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section><CultivationStory/><CompanyFAQ/><SiteFooter/></main>}
