export const articles = [
 {slug:"from-pond-to-product", category:"Inside Sea Pearl", title:"From the pond to your product", image:"PHOTO-2024-07-12-12-50-31-2.jpg", intro:"A closer look at how cultivation, ingredient supply and product development connect at Sea Pearl Biotech.", sections:[
 ["It starts in Ahmedabad", "Sea Pearl Biotech was founded in March 2016 in Ahmedabad, Gujarat. Spirulina cultivation is central to the company’s work, alongside ingredient supply and white-label manufacturing. The cultivation photographs on this website come from the company’s existing image library."],
 ["A product begins with a brief", "A food business, a supplement brand and a personal-care team can need very different formats. The first conversation should cover the proposed application, the required format, the intended market and the documentation needed by the product team."],
 ["Looking beyond the ingredient", "Sea Pearl’s white-label services extend the conversation to formulation, packaging, labelling and distribution support. Bring a clear brief to the team so the practical requirements of your project can be discussed together."]]},
 {slug:"choosing-your-spirulina-format", category:"Ingredient guide", title:"Powder, flakes or tablets? Start with the format.", image:"Seapearl-Product-Images.002.jpeg", intro:"A practical starting point for exploring the formats in the Sea Pearl spirulina range.", sections:[
 ["Begin with the finished product", "Describe what you want to make before selecting a format. A recipe ingredient, a finished tablet and a capsule involve different development decisions. Share the intended use and ask the team which formats are appropriate for your brief."],
 ["Explore the range", "The Sea Pearl portfolio includes spirulina powder, flakes and granules, tablets, capsules, frozen spirulina and Spirulina D2B12. Individual product pages bring these formats together with the original product images."],
 ["Ask for the details that matter", "Confirm the composition, specification, packaging, storage requirements and order quantities for the product you are considering. Use current product documentation for your evaluation rather than transferring specifications from another format."]]},
 {slug:"planning-a-white-label-product", category:"Brand development", title:"Your first white-label conversation: what to bring", image:"Seapearl-Product-Images.006.jpeg", intro:"A focused brief makes it easier to discuss an algae-based product under your own brand.", sections:[
 ["Define the idea", "Start with your intended customer, product category and sales market. Describe the format you have in mind and the reason it fits your range. If the idea is still taking shape, explain the choices you are trying to resolve."],
 ["Think about the pack", "Discuss pack size, label requirements, design assets and the information your team needs to prepare the packaging. Sea Pearl’s existing service description includes packaging and labelling support as part of its white-label work."],
 ["Agree the next step", "Ask which samples, technical documents and project details are needed before progressing. Confirm quantities and timing directly with the team; they depend on the product and project requirements."]]}
];
