export const productResearch:Record<string,{description:string;considerations:string[];notice?:string}>={
 "spirulina":{description:"Spirulina is a blue-green microalgae used as a food and supplement ingredient. Sea Pearl’s original product information presents powder, tablet and flake formats, with applications including smoothies, salads and supplements.",considerations:["Choose a format around mixing, texture and the intended product.","Request the current composition, microbiological specification and storage guidance."]},
 "spirulina-capsule":{description:"The capsule range offers spirulina in a portioned format for supplement product development. It sits alongside the company’s powder, tablet, flake and frozen offerings.",considerations:["Confirm fill weight, capsule material and ingredient composition.","Discuss bulk supply or your own brand’s packaging and labelling."]},
 "spirulina-d2b12":{description:"A specialty spirulina product listed in the Sea Pearl portfolio under the name Spirulina D2B12. Confirm the vitamin composition and final specification with the product team before developing a label or placing an order.",notice:"Formulation clarification needed: the original product title says D2B12, while its description refers to vitamin D3 and B12.",considerations:["Request the exact vitamin forms and quantities.","Confirm formulation, supporting analysis and suitability for your intended market."]},
 "spirulina-flakes-granules":{description:"A textured spirulina format for food and ingredient development. Flakes and granules offer a different physical format from fine powder, capsules and compressed tablets.",considerations:["Discuss the required particle size and texture.","Confirm handling, moisture specification and packaging for your application."]},
 "spirulina-tablets":{description:"Spirulina in a tablet format, part of Sea Pearl’s own product portfolio. This format can be discussed alongside capsule and powder options for a branded product range.",considerations:["Request tablet weight, composition and a current product specification.","Discuss pack count, packaging and white-label requirements."]},
 "frozen-spirulina":{description:"The original product page describes spirulina harvested and rapidly frozen, with suggested food uses including smoothies, juices and recipes. This is a distinct format from dried powder and tablets.",considerations:["Confirm cold-chain, transport and storage requirements before ordering.","Request pack sizes, shelf life and handling guidance for the specific product."]},
 "phycocyanin":{description:"Phycocyanin is the blue, water-soluble pigment-protein complex associated with spirulina. Sea Pearl lists both powder and capsule formats, with food and drink development among the uses described on its website.",considerations:["Discuss the required colour strength and ingredient specification.","Confirm suitability for your formulation and destination-market requirements."]},
 "phycocyanin-capsule":{description:"A capsule presentation of the blue spirulina-derived pigment in Sea Pearl’s portfolio. Explore this alongside the powder ingredient when choosing the format for a supplement range.",considerations:["Request phycocyanin content, capsule composition and fill weight.","Confirm the product’s current specification and available quality documents."]},
 "omega-3":{description:"The original Sea Pearl listing describes algae-based omega-3 as an alternative to animal-derived sources. Discuss the precise ingredient composition and format with the product team.",considerations:["Request the fatty-acid profile and exact DHA/EPA content.","Confirm source, carriers, storage conditions and supporting analysis."]},
 "omega-3-capsules":{description:"Sea Pearl’s capsule listing describes an algal-oil omega-3 format. Confirm the finished product specification rather than assuming every capsule has the same fatty-acid profile or strength.",considerations:["Request oil source, DHA/EPA content and capsule-shell material.","Discuss packaging, stability, shelf life and market-specific labelling."]},
 "astaxanthin":{description:"Astaxanthin is a red carotenoid included in Sea Pearl’s specialty ingredient range. The original product page identifies microalgae among its sources; ask the team to confirm the source and specification of the offered ingredient.",considerations:["Confirm source, concentration, carrier and physical format.","Request the relevant analysis and intended-application documentation."]},
 "astaxanthin-capsules":{description:"The capsule format of astaxanthin is listed alongside the specialty ingredient in Sea Pearl’s portfolio. Product strength and composition should be confirmed for the particular formulation.",considerations:["Request the amount of astaxanthin per capsule and complete composition.","Discuss capsule material, pack size and white-label options."]},
 "beta-carotene":{description:"Beta carotene is an orange-yellow carotenoid listed in the specialty ingredient portfolio. Sea Pearl’s product page introduces it as a vitamin A precursor; the source, concentration and grade of the supplied product require confirmation.",considerations:["Request product source, assay, carriers and physical format.","Discuss formulation suitability and requirements for your target market."]},
 "squalene-powder":{description:"Squalene powder appears in Sea Pearl’s cosmetic and supplement ingredient portfolio. Its original page mentions both plant and animal sources of squalene in general, but does not identify the source of this specific product.",notice:"Source confirmation needed: do not assume this product is algae-derived or vegan without the supplier’s specification.",considerations:["Confirm source, purity, carrier and powder composition.","Request documentation relevant to your formulation and sourcing policy."]},
 "vegan-protein-powder":{description:"Sea Pearl describes an algae-based protein powder, mentioning spirulina and chlorella, for uses such as shakes, smoothies and baked goods. Ask the team for the exact blend and nutritional analysis of the offered product.",considerations:["Confirm protein content, ingredient composition and allergen information.","Discuss sensory requirements, solubility and the intended food application."]}
};
