import fs from 'node:fs/promises';
async function edit(file,pairs){let s=await fs.readFile(file,'utf8');for(const [a,b]of pairs)s=s.replaceAll(a,b);await fs.writeFile(file,s);}
await edit('app/page.tsx',[[ (await fs.readFile('app/page.tsx','utf8')), 'import { EditorialHome } from "@/components/editorial-home";\nexport default function Home(){return <EditorialHome/>;}\n' ]]);
for(const file of ['app/ingredients/page.tsx','app/ingredients/[slug]/page.tsx']){
 await edit(file,[['{ products }','{ products, productImage }'],['<span className="bio-sphere s-one"/><span className="bio-sphere s-two"/>','<img className="original-product-image" src={productImage(p.slug)} alt={p.name} loading="lazy"/>'],['An editorial catalogue<br/>for product development.','Algae ingredients.<br/>A world of possibilities.'],['Explore the current Sea Pearl Biotech range. Product specifications, packaging and minimum order quantities are provided through a qualified enquiry.','Explore spirulina, phycocyanin and our specialty ingredient range. Find a format for your application, then speak to our team about specifications and availability.'],['<div className="fake-search"><Search size={17}/> Search portfolio</div>','<a href="/shop" className="text-link">Our own products · Shop now ↗</a>'],['A format for qualified product conversations.','Find the right fit for your product.'],['Sea Pearl Biotech lists {p.name} within its ingredient range. Final descriptions, origin, purity, shelf life, dosage, packaging and minimum order information require approved technical documents.','{p.name} is part of our algae ingredient portfolio. Speak to our team about your intended application, preferred format and order requirements. We can discuss the relevant product information with you.'],['Technical status','Product enquiries'],['Documentation required','Contact our team']]);
}
await edit('app/about/page.tsx',[
 ['<div className="abstract-culture" aria-hidden="true"><span/><span/><span/></div>',''],
 ['<section className="section editorial-grid">','<figure className="section about-photo"><img src="/original/PHOTO-2024-07-12-12-50-31-2.jpg" alt="Sea Pearl spirulina cultivation ponds"/><figcaption>Our cultivation environment in Gujarat.</figcaption></figure><section className="section editorial-grid">'],
 ['Our new digital experience separates confirmed company information from claims that still require documentation. That same clarity should guide every technical conversation.','Our work also includes product formulation, packaging and labelling support for businesses developing their own spirulina range. We collaborate with brands to understand their product vision and the requirements of their market.'],
 ['Sea Pearl’s existing materials describe controlled environments, aquaculture technology, water management, harvesting and testing. Detailed operating claims remain subject to company verification.','Our cultivation approach brings water management, nutrient supply, harvesting and quality-control checkpoints together. The growing environment is the starting point for the ingredients we supply.']]);
await edit('app/applications/page.tsx',[
 ['Every application begins with technical fit, documentation and responsible claim review.','Tell us about your product and we will help you explore the formats in our range.'],
 ['<section className="section boundary-panel"><p className="section-label">A responsible boundary</p><h2>Potential is not the same as proof.</h2><p>We do not infer therapeutic outcomes, regulatory status or nutritional claims from a product name. Application language is reviewed against current technical and compliance documents before publication.</p></section>','<section className="section boundary-panel"><p className="section-label">Develop with us</p><h2>What are you working on?</h2><p>Share your product category, preferred ingredient format and market. Our team can discuss the next steps for your application.</p><a className="button button-primary" href="/contact">Talk to our team ↗</a></section>'],
 ['for qualified product briefs.','for product development.'],['for reviewed supplement concepts.','for supplement development.'],['Early-stage ingredient conversations without unsupported clinical or regulatory claims.','Ingredient supply discussions for healthcare product-development teams.']]);
await edit('app/manufacturing/page.tsx',[
 ['Sea Pearl Biotech’s existing materials describe controlled spirulina cultivation and processing. Capacity, facility specifications and approvals remain subject to documentation.','We cultivate spirulina in a managed growing environment. Our work spans water and nutrient management, harvesting and processing, with quality-control checkpoints along the way.'],
 ['<div className="process-rings" aria-hidden="true"><span/><span/><span/></div>','<img className="manufacturing-photo" src="/original/PHOTO-2024-07-12-12-50-29-2.jpg" alt="Sea Pearl cultivation ponds"/>']]);
await edit('app/layout.tsx',[['/favicon.svg','/original/cropped-sea-pearl-3-06-192x192.png']]);
await edit('lib/products.ts',[
 ['Technical content and specifications require company approval.','Explore our Spirulina D2B12 range with the product team.'],['for approved formulations.','for your product range.'],['for approved supplement briefs.','for supplement product development.'],['for qualified product development.','for product development.'],['for reviewed applications.','for food and ingredient applications.'],['Capsule format; final claims require technical review.','Phycocyanin in capsule form, part of our algae product range.'],['for reviewed formulations.','for your formulation brief.'],['Finished format; technical claims require documentation.','Astaxanthin capsules from the Sea Pearl product portfolio.'],['A naturally associated pigment category for product enquiries.','Explore beta carotene within our specialty ingredient range.'],['Technical specifications are supplied after qualification.','Speak to our team about squalene powder and product specifications.']]);
