import { productResearch } from "@/lib/product-research";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Check, FileText } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { products, productImage } from "@/lib/products";

export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);return {title:`${p?.name||"Ingredient"} | Sea Pearl Biotech`,description:p?`${p.name} from Sea Pearl Biotech. Explore the ${p.form.toLowerCase()} format and request product specifications.`:undefined};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const p=products.find(x=>x.slug===slug); if(!p)notFound(); const research=productResearch[p.slug]; return <main><div className="product-detail-top"><SiteHeader/><div className="product-detail section"><div className="product-detail-copy"><Link className="back-link" href="/ingredients"><ArrowLeft size={16}/> All ingredients</Link><p className="section-label light">{p.family}</p><h1>{p.name}</h1><p>{p.note}</p><div className="hero-actions"><Link className="button button-primary" href={`/contact?product=${p.slug}`}>Request specifications <ArrowUpRight size={18}/></Link></div></div><div className="detail-visual" style={{"--accent":p.accent} as React.CSSProperties}><img className="original-product-image" src={productImage(p.slug)} alt={p.name} loading="lazy"/><div>{p.form}</div></div></div></div>
<section className="section detail-content"><div><p className="section-label">What it is</p><h2>Find the right fit for your product.</h2><p>{research.description}</p></div><div className="inset-spec"><div><span>Available format</span><strong>{p.form}</strong></div><div><span>Application areas</span><strong>{p.applications.join(", ")}</strong></div><div><span>Product enquiries</span><strong>Contact our team</strong></div></div></section>
<section className="section product-research"><p className="section-label">Planning your formulation</p><h2>Details worth discussing.</h2><ul>{research.considerations.map(item=><li key={item}>{item}</li>)}</ul>{research.notice&&<p><strong>Please confirm:</strong> {research.notice}</p>}<a className="source-caption" href={`https://seapearlbiotech.com/${p.slug}/`} target="_blank" rel="noreferrer">Original Sea Pearl product information ↗</a></section><section className="section doc-panel"><div><FileText/><h2>Quality and documentation</h2><p>Request the current technical data, certification evidence and logistics details for this product.</p></div><ul><li><Check/> Technical specification table</li><li><Check/> Approved quality documents</li><li><Check/> Packaging and logistics options</li></ul><Link className="button button-dark" href={`/contact?product=${p.slug}`}>Talk to an ingredient specialist <ArrowUpRight size={18}/></Link></section><SiteFooter/></main>}
