import { sitePath } from "@/lib/site-path";
import { WhiteLabelDepth, CompanyFAQ } from "@/components/company-depth";
import Link from "@/components/site-link";
import { ArrowDown, ArrowUpRight, Beaker, ClipboardCheck, Package, Sprout, Waves } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
const steps=[{i:Sprout,t:"Cultivation brief",p:"Align ingredient, format and intended application."},{i:Waves,t:"Cultivation",p:"Manage growing conditions and culture development."},{i:Beaker,t:"Processing",p:"Move toward the required ingredient or finished format."},{i:ClipboardCheck,t:"Quality review",p:"Confirm the documentation required for the brief."},{i:Package,t:"Packaging discussion",p:"Review pack, label and logistics requirements."}];
export const metadata={title:"White-Label Algae Ingredient Manufacturing | Sea Pearl Biotech"};
export default function ManufacturingPage(){return <main><div className="manufacturing-top"><SiteHeader/><div className="page-hero dark"><p className="section-label light">Manufacturing & services</p><h1>From culture<br/>to commercial brief.</h1><p>Ingredient supply, spirulina cultivation and white-label product support—organized around a clear development pathway.</p><a className="scroll-cue" href="#workflow"><ArrowDown/> See the workflow</a></div><img className="manufacturing-photo" src={sitePath("/original/PHOTO-2024-07-12-12-50-29-2.jpg")} alt="Sea Pearl cultivation ponds"/></div><section className="section service-columns"><article><span>01</span><h2>Spirulina manufacturer</h2><p>We cultivate spirulina in a managed growing environment. Our work spans water and nutrient management, harvesting and processing, with quality-control checkpoints along the way.</p></article><article><span>02</span><h2>Ingredient supplier</h2><p>A portfolio of algae-based and specialty ingredient formats for product-development teams across multiple industries.</p></article><article><span>03</span><h2>White-label manufacture</h2><p>Collaborative discussions spanning format, formulation direction, packaging and labelling requirements.</p></article></section><section id="workflow" className="workflow-section"><div className="section"><p className="section-label light">Development pathway</p><h2>A structured route from brief to handoff.</h2><div className="workflow-list">{steps.map(({i:I,t,p},n)=><div key={t}><span>0{n+1}</span><I/><h3>{t}</h3><p>{p}</p></div>)}</div><Link className="button button-primary" href={sitePath("/contact")}>Start a manufacturing enquiry <ArrowUpRight size={18}/></Link></div></section><WhiteLabelDepth/><CompanyFAQ/><SiteFooter/></main>}
